# Generated by Django 4.2.1 on 2023-05-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenproduct',
            name='productID',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
    ]
