# Generated by Django 4.2.1 on 2023-05-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cart_product_qty_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.ImageField(upload_to=''),
        ),
    ]
